from . import cvaltare_curriculum
from . import cvaltare_curriculumtag
from . import cvaltare_oferta
from . import cvaltare_oferta_line
from . import cvaltare_entrevista
from . import cvaltare_calendar
from . import hr_applicant
from . import hr_employee
from . import cva_partner
from . import cvaltare_settings
